export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const BASCET_ROUTE = '/bascet'
export const DEVICE_ROUTE = '/device'
export const USER_ROUTE = '/lk'
